apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb

spec:
  serviceName: "mongodb"         # This must match the headless service name
  replicas: 2
  selector:
    matchLabels:
      app: mongodb

  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db    # MongoDB stores its data here

      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-pvc   # Referencing your pre-created PVC
