apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb

spec:
  clusterIP: None                # Headless service to enable stable DNS for StatefulSet
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
