apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsdbapp
  labels:
    app: nodejsdbapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejsdbapp
  template:
    metadata:
      labels:
        app: nodejsdbapp
    spec:
      containers:
      - name: nodejsdbapp
        image: dheeraj394/node-mongo-db:08
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: mongodb://mongodb:27017/mydb
