apiVersion: apps/v1               # API version for Deployment resource
kind: Deployment                  # This resource is a Deployment, which manages Pods
metadata:
  name: nodejsdbapp               # Name of the Deployment
  labels:
    app: nodejsdbapp              # Labels to identify this Deployment and its Pods
spec:
  replicas: 2                     # Number of Pod replicas to run
  selector:
    matchLabels:
      app: nodejsdbapp            # Selector to match Pods managed by this Deployment
  template:
    metadata:
      labels:
        app: nodejsdbapp          # Labels assigned to Pods created by this Deployment
    spec:
      containers:
      - name: nodejsdbapp         # Container name inside the Pod
        image: dheeraj394/node-mongo-db:03  # Docker image for the app container
        ports:
        - containerPort: 3000     # Container listens on port 3000
        env:                      # Environment variables injected into the container
        - name: MONGO_HOST        # MongoDB hostname, matches key in ConfigMap
          valueFrom:
            configMapKeyRef:
              name: mongo-config  # Refers to ConfigMap named 'mongo-config'
              key: MONGO_HOST    # Key in ConfigMap to get value from
        - name: MONGO_PORT        # MongoDB port number, from ConfigMap
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_PORT
        - name: MONGO_DB          # MongoDB database name, from ConfigMap
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_DB
        - name: PORT              # Application port, fixed as 3000 here
          value: "3000"
