apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsdbapp
  labels:
    app: nodejsdbapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejsdbapp
  template:
    metadata:
      labels:
        app: nodejsdbapp
    spec:
      containers:
      - name: nodejsdbapp
        image: dheeraj394/node-mongo-db:09
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_URL
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_PORT
         - name: MONGO_DB
           valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_DB
        - name: PORT
          value: "3000"   # your app port (optional)
