# Define a PersistentVolume resource
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/mongodb

---
# Define a PersistentVolumeClaim resource to claim storage from the PersistentVolume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  # add namespace if not default, e.g. namespace: your-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeMode: Filesystem
