apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-mongodb-0
  namespace: nodejsdbapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
